services:
  weatherapi-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: weatherapi-forecast_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  weatherapi-userdb:
    image: postgres:17
    container_name: weatherapi-user_db
    environment:
      POSTGRES_DB: UserDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    


  weatherapi-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherapi-api
    depends_on:
      - weatherapi-db
      - weatherapi-userdb
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__WeatherDb: "Server=weatherapi-db,1433;Database=WeatherDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      ConnectionStrings__UserDb: "Host=weatherapi-userdb;Port=5432;Database=UserDB;Username=postgres;Password=YourStrong!Passw0rd"
      OpenAI__ApiKey: "${OPENAI_API_KEY:-}"
    ports:
      - "5001:8080"
        

volumes:
  postgres_data:
  sqlserver-data:
