// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAPI.Infrastructure.Persistence;

#nullable disable

namespace WeatherAPI.Infrastructure.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260405120043_MakeForecastFetchUpdatedAtNullable")]
    partial class MakeForecastFetchUpdatedAtNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherAPI.Domain.Entities.FetchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ForecastFetchId")
                        .HasColumnType("int")
                        .HasColumnName("forecast_fetch_id");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("PK_FetchLog");

                    b.HasIndex("ForecastFetchId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FetchLog_ForecastFetch");

                    b.ToTable("FetchLog", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.ForecastFetch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fetched_at");

                    b.Property<short>("LocationId")
                        .HasColumnType("smallint")
                        .HasColumnName("location_id");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("response_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_ForecastFetch");

                    b.HasIndex("LocationId");

                    b.ToTable("ForecastFetch", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.ForecastFetchUnit", b =>
                {
                    b.Property<int>("ForecastFetchId")
                        .HasColumnType("int")
                        .HasColumnName("forecast_fetch_id");

                    b.Property<byte>("MetricId")
                        .HasColumnType("tinyint")
                        .HasColumnName("metric_id");

                    b.Property<byte>("UnitId")
                        .HasColumnType("tinyint")
                        .HasColumnName("unit_id");

                    b.HasKey("ForecastFetchId", "MetricId")
                        .HasName("PK_ForecastFetchUnit");

                    b.HasIndex("MetricId");

                    b.HasIndex("UnitId");

                    b.ToTable("ForecastFetchUnit", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.HourlyForecast", b =>
                {
                    b.Property<int>("ForecastFetchId")
                        .HasColumnType("int")
                        .HasColumnName("forecast_fetch_id");

                    b.Property<DateTime>("ForecastTime")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("forecast_time");

                    b.Property<decimal?>("AirPressureAtSeaLevel")
                        .HasPrecision(6, 1)
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("air_pressure_at_sea_level");

                    b.Property<decimal?>("AirTemperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("air_temperature");

                    b.Property<byte?>("Cloudiness")
                        .HasColumnType("tinyint")
                        .HasColumnName("cloudiness");

                    b.Property<byte?>("Humidity")
                        .HasColumnType("tinyint")
                        .HasColumnName("humidity");

                    b.Property<decimal?>("PrecipitationAmount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("precipitation_amount");

                    b.Property<byte?>("WeatherSymbolId")
                        .HasColumnType("tinyint")
                        .HasColumnName("weather_symbol_id");

                    b.Property<decimal?>("WindDirection")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("wind_direction");

                    b.Property<decimal?>("WindSpeed")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("wind_speed");

                    b.HasKey("ForecastFetchId", "ForecastTime")
                        .HasName("PK_HourlyForecast");

                    b.HasIndex("WeatherSymbolId");

                    b.ToTable("HourlyForecast", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.Location", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short?>("Altitude")
                        .HasColumnType("smallint")
                        .HasColumnName("altitude");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_Location");

                    b.HasIndex("Latitude", "Longitude", "Altitude")
                        .IsUnique()
                        .HasDatabaseName("UQ_Location_Latitude_Longitude_Altitude")
                        .HasFilter("[altitude] IS NOT NULL");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.Metric", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_Metric");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Metric_Name");

                    b.ToTable("Metric", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.Unit", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("desc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("display_name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PK_Unit");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("UQ_Unit_Value");

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.WeatherSymbol", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("PK_WeatherSymbol");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_WeatherSymbol_Code");

                    b.ToTable("WeatherSymbol", (string)null);
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.FetchLog", b =>
                {
                    b.HasOne("WeatherAPI.Domain.Entities.ForecastFetch", "ForecastFetch")
                        .WithOne("FetchLog")
                        .HasForeignKey("WeatherAPI.Domain.Entities.FetchLog", "ForecastFetchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FetchLog_ForecastFetch");

                    b.Navigation("ForecastFetch");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.ForecastFetch", b =>
                {
                    b.HasOne("WeatherAPI.Domain.Entities.Location", "Location")
                        .WithMany("ForecastFetches")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForecastFetch_Location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.ForecastFetchUnit", b =>
                {
                    b.HasOne("WeatherAPI.Domain.Entities.ForecastFetch", "ForecastFetch")
                        .WithMany("ForecastFetchUnits")
                        .HasForeignKey("ForecastFetchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForecastFetchUnit_Fetch");

                    b.HasOne("WeatherAPI.Domain.Entities.Metric", "Metric")
                        .WithMany("ForecastFetchUnits")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForecastFetchUnit_Metric");

                    b.HasOne("WeatherAPI.Domain.Entities.Unit", "Unit")
                        .WithMany("ForecastFetchUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForecastFetchUnit_Unit");

                    b.Navigation("ForecastFetch");

                    b.Navigation("Metric");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.HourlyForecast", b =>
                {
                    b.HasOne("WeatherAPI.Domain.Entities.ForecastFetch", "ForecastFetch")
                        .WithMany("HourlyForecasts")
                        .HasForeignKey("ForecastFetchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HourlyForecast_Fetch");

                    b.HasOne("WeatherAPI.Domain.Entities.WeatherSymbol", "WeatherSymbol")
                        .WithMany("HourlyForecasts")
                        .HasForeignKey("WeatherSymbolId")
                        .HasConstraintName("FK_HourlyForecast_Symbol");

                    b.Navigation("ForecastFetch");

                    b.Navigation("WeatherSymbol");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.ForecastFetch", b =>
                {
                    b.Navigation("FetchLog");

                    b.Navigation("ForecastFetchUnits");

                    b.Navigation("HourlyForecasts");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.Location", b =>
                {
                    b.Navigation("ForecastFetches");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.Metric", b =>
                {
                    b.Navigation("ForecastFetchUnits");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.Unit", b =>
                {
                    b.Navigation("ForecastFetchUnits");
                });

            modelBuilder.Entity("WeatherAPI.Domain.Entities.WeatherSymbol", b =>
                {
                    b.Navigation("HourlyForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
